---
- name: fetch ceph red hat development repository
  uri:
    url: https://shaman.ceph.com/api/repos/ceph/{{ ceph_dev_branch }}/{{ ceph_dev_sha1 }}/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/repo
    return_content: yes
  register: ceph_dev_yum_repo

- name: configure ceph red hat development repository
  copy:
    content: "{{ ceph_dev_yum_repo.content }}"
    dest: /etc/yum.repos.d/ceph-dev.repo
    owner: root
    group: root
    backup: yes

- name: fetch nfs-ganesha red hat development repository
  uri:
    url: https://shaman.ceph.com/api/repos/nfs-ganesha/next/latest/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/flavors/{{ nfs_ganesha_flavor }}/repo
    return_content: yes
  register: nfs_ganesha_dev_yum_repo
  when:
    - nfs_group_name in group_names
    - nfs_ganesha_dev

- name: add nfs-ganesha development repository
  copy:
    content: "{{ nfs_ganesha_dev_yum_repo.content }}"
    dest: /etc/yum.repos.d/nfs-ganesha-dev.repo
    owner: root
    group: root
    backup: yes
  when:
    - nfs_group_name in group_names
    - nfs_ganesha_dev

- name: set_fact ceph_iscsi_repos
  set_fact:
    ceph_iscsi_repos:
      - ceph-iscsi-config
      - tcmu-runner
  when:
    - ceph_iscsi_config_dev
    - iscsi_gw_group_name in group_names

- name: fetch ceph-iscsi-config red hat development repository
  uri:
    url: https://shaman.ceph.com/api/repos/{{ item }}/{{ ceph_dev_branch }}/{{ ceph_dev_sha1 }}/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/repo
    return_content: yes
  register: ceph_iscsi_config_dev_yum_repo
  with_items: "{{ ceph_iscsi_repos }}"
  when:
    - ceph_iscsi_config_dev
    - iscsi_gw_group_name in group_names

- name: configure ceph-iscsi-config red hat development repository
  copy:
    content: "{{ item.0.content }}"
    dest: "/etc/yum.repos.d/{{ item.1 }}-dev.repo"
    owner: root
    group: root
    backup: yes
  with_together:
    - "{{ ceph_iscsi_config_dev_yum_repo.results }}"
    - "{{ ceph_iscsi_repos }}"
  when:
    - ceph_iscsi_config_dev
    - iscsi_gw_group_name in group_names
